name: tugas_akhir
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  gap: ^3.0.1
  get: ^4.6.6
  url_launcher: ^6.2.1
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
- assets/